### ISSUE TITLE
A user’s perspective on using JuMP in an academic project | Mathieu Tanneau | JuliaCon 2022 

### ISSUE THREAD

**Issue by digital-carver** [JuliaCommunity/YouTubeVideoTimestamps#209]
Link to the talk: https://www.youtube.com/watch?v=61fnHmri7_Q

Homepage of the RAMC project: https://ramc.isye.gatech.edu/
JuMP on Github: https://github.com/jump-dev/JuMP.jl/
JuMP documentation: https://jump.dev/JuMP.jl/stable/

00:06 Introduction
00:44 What is the RAMC project?
01:46 Four pillars of the RAMC methodology
02:27 Who we are: the RAMC team
04:50 Questions about JuMP usage
05:10 Why JuMP instead of XX? 
09:22 The scope of the Optimization problem
10:37 Our typical Optimization workflow
11:41 Common sources of errors
12:57 Handling and debugging errors
16:09 Access to the MOI backend
17:42 Room for improvement: Feature improvements
18:21 Room for improvement: Performance improvements
20:51 Conclusions

**Comment by KZiemian** [comment]
A little tweaked version of your work.

Contents
00:00 Opening and introduction
00:44 What is the RAMC project?
01:46 Four pillars of the RAMC methodology
02:27 Who we are: the RAMC team
04:50 Questions about JuMP usage
05:10 Why JuMP instead of XX?
09:22 The scope of the Optimization problem
10:37 Our typical Optimization workflow
11:41 Common sources of errors
12:57 Handling and debugging errors
16:09 Access to the MOI backend
17:42 Room for improvement: Feature improvements
18:21 Room for improvement: Performance improvements
20:51 Conclusions

Resources
Homepage of the RAMC project, [link](https://ramc.isye.gatech.edu/).
JuMP [repository](https://github.com/jump-dev/JuMP.jl/).
JuMP [documentation](https://jump.dev/JuMP.jl/stable/).

**Comment by KZiemian** [comment]
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment]
From what I see that we can close the issue.
